stages:
  - triage

image: ruby:2.4-alpine

before_script:
  - gem install gitlab-triage --no-doc

.triage: &triage
  stage: triage
  script:
    - gitlab-triage --token $TRIAGE_API_TOKEN --project-id $CI_PROJECT_PATH $TRIAGE_OPTS

variables:
  TRIAGE_OPTS: ""

run:triage:
  <<: *triage
  retry: 2
  only:
    - schedules

run:triage:dry-run:
  <<: *triage
  stage: triage
  variables:
    TRIAGE_OPTS: "--dry-run"
  except:
    - schedules

run:triage:dry-run:debug:
  <<: *triage
  stage: triage
  variables:
    TRIAGE_OPTS: "--dry-run --debug"
  when: manual
