stages:
  - triage

gitlab-triage:
  stage: triage
  image: ruby:2.4-alpine
  script:
    - gem install gitlab-triage --no-doc
    - gitlab-triage --token $API_TOKEN --project-id $CI_PROJECT_PATH
  only:
    - schedules

