resource_rules:
  issues:
    rules:
      - name: Mark stale issues with no milestone for closure
        conditions:
          date:
            attribute: updated_at
            condition: older_than
            interval_type: months
            interval: 12
          milestone:
            - No Milestone
          state: opened
        actions:
          labels:
            - awaiting feedback
            - auto updated
          mention:
            - markglenfletcher
          comment: |
            Hi,

            First of all, thank you for raising an issue to help improve the GitLab Runner product. We're sorry about this, but this particular issue has gone unnoticed for quite some time. To establish order in the GitLab-Runner Issue Tracker, we must ensure that every issue is correctly labelled and triaged, to get the proper attention.

            We are automatically labelling this issue for attention as it meets the following criteria:
            * No activity in the past 12 months
            * No milestone (unscheduled)

            We'd like to ask you to help us out and determine whether this issue should be stay open or be closed.

            If this issue is reporting a bug, please can you attempt to reproduce on the latest version of the runner, to help us to understand whether the bug still needs our attention.

            If this issue is proposing a new feature, please can you verify whether the feature proposal is still relevant.

            Thanks for your help

      - name: Mark stale issues for closure
        conditions:
          date:
            attribute: updated_at
            condition: older_than
            interval_type: months
            interval: 3
          labels:
            - No Label
          state: opened
        actions:
          labels:
            - awaiting feedback
            - auto updated
          mention:
            - markglenfletcher
          comment: |
            Hi,

            First of all, thank you for raising an issue to help improve the GitLab Runner product. We're sorry about this, but this particular issue has gone unnoticed for quite some time. To establish order in the GitLab-Runner Issue Tracker, we must ensure that every issue is correctly labelled and triaged, to get the proper attention.

            We are automatically labelling this issue for attention as it meets the following criteria:
            * No activity in the past 3 months
            * Unlabelled

            We'd like to ask you to help us out and determine whether this issue should be stay open or be closed.

            If this issue is reporting a bug, please can you attempt to reproduce on the latest version of the runner, to help us to understand whether the bug still needs our attention.

            If this issue is proposing a new feature, please can you verify whether the feature proposal is still relevant.

            Thanks for your help

      - name: Mark stale bugs for closure
        conditions:
          date:
            attribute: updated_at
            condition: older_than
            interval_type: months
            interval: 6
          labels:
            - bug
          milestone:
            - No Milestone
          state: opened
        actions:
          labels:
            - awaiting feedback
            - auto updated
          mention:
            - markglenfletcher
          comment: |
            Hi,

            First of all, thank you for raising an issue to help improve the GitLab Runner product. We're sorry about this, but this particular issue has gone unnoticed for quite some time. To establish order in the GitLab-Runner Issue Tracker, we must ensure that every issue is correctly labelled and triaged, to get the proper attention.

            We are automatically labelling this issue for attention as it meets the following criteria:
            * Issue is open
            * No activity in the past 6 months
            * Labelled as a bug
            * Unscheduled (no milestone)

            We'd like to ask you to help us out and determine whether this issue should be stay open or be closed.

            Because this issue is reporting a bug, please can you attempt to reproduce on the latest version of the runner, to help us to understand whether the bug still needs our attention.

            Thanks for your help

      - name: Close non-updated issues
        conditions:
          date:
            attribute: updated_at
            condition: older_than
            interval_type: weeks
            interval: 2
          labels:
            - awaiting feedback
            - auto updated
          state: opened
        actions:
          labels:
            - auto closed
          mention:
            - markglenfletcher
          status: close
          comment: |
            Closing this issue down in accordance with our [Issue Triage Policies](https://gitlab.com/gitlab-org/gitlab-runner/tree/master/.triage-policies.yml). Please reopen the issue if you feel that the issue is still relevant. Thanks!

      - name: Assign CI/CD label to Deliverable issues
        conditions:
          state: opened
          labels:
            - Deliverable
        actions:
          labels:
            - CI/CD
      - name: Assign CI/CD label to Stretch issues
        conditions:
          state: opened
          labels:
            - Stretch
          actions:
            labels:
              - CI/CD

  merge_requests:
    rules: []
